config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
#
# ユーザーモデル定義
#
# 生成に利用したrailsコマンド
# rails generate model User name:string email:string
# rails generate migration add_index_to_users_email
# rails generate migration add_password_digest_to_users password_digest:string
#
class User < ApplicationRecord
  # データ保存前にメアド文字列をすべて小文字に変換する
  # これは、DB内で大文字小文字を区別を無くすため（メアドというものはそういうものなので）
  before_save { email.downcase! }
  # 名前は必ず存在し、長さは50文字以下とする
  validates :name,  presence: true, length: { maximum: 50 }
  # メアドの正規表現(メアドの正当性をチェックするために定義)
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  # メアドは必ず存在、最大文字列長255文字、形式を上記正規表現で限定、かつ、
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  # セキュアなpassword
  has_secure_password
  validates :password, length: { minimum: 6 }, presence: true

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    # test等にて最小コストを要求されることを想定し、その場合は最小コストとする
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    # ハッシュ（ダイジェスト）を求める
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  # SessionsHelperをミックスイン
  include SessionsHelper

end

app/controllers/sessions_controller.rb
# セッションコントローラ
# 'rails generate controller Sessions new' で生成
class SessionsController < ApplicationController

  # 新規セッション作成(log-in UI)
  def new
  end

  # 新規セッション作成
  def create
    # 登録済ユーザか否かを確認するために、dbを検索する
    @user = User.find_by(email: params[:session][:email].downcase)

    # userがnilでなく、認証できるなら、成功
    # ちなみに、has_secure_passwordをUserモデルに追加したことで、
    # そのオブジェクト内でauthenticateメソッドが使えるようになっている
    if @user && @user.authenticate(params[:session][:password])

      # ユーザーログイン後にユーザー情報のページにリダイレクトする
      # log_inはSessionsHelperで定義されたメソッド
      log_in @user

      # 永続化
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)

      # 以下の実行により、/users/#{user.id}へ飛ばす
      # 次のrailsおよびrubyのルール等により、redirect_to user
      # と書くだけで良い！
      # * 絶対パスへはuser_url(@user.id)で求めることが出来る
      # * リンクのパスとしてモデルオブジェクトが渡されると自動で
      #   idにリンクされるので、.idを省略可
      # * _urlヘルパーは、省略できる
      # * Rubyでは、()は省略できる 
      redirect_to @user

    # 認証失敗の場合は、エラー
    else

      # エラーメッセージを作成する
      flash.now[:danger] = 'Invalid email/password combination' 

      # ログイン画面にもどる
      render 'new'

    end
  end

  # セッション削除(log-out)
  def destroy
    # Helperのlog_outメソッドを呼ぶ
    log_out if logged_in?
    # ルートページへ飛ばす。root_urlは、rootのurlを返す。
    #   ちなみに、root_pathは、/を返す。help_pathは、/helpを、、などなど
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users/id
  def show
    @user = User.find(params[:id])
    #デバッガ―をコンソールで実行できる！！
    #debugger
  end

  # "rails generate controller Users new"で生成
  def new
    @user = User.new
    #debugger
  end

  def create
    @user = User.new(user_params)
    #debugger
    if @user.save
      # 登録成功なので、ログインする
      log_in @user
      # flashを設定する。次のリダイレクト先でflashをアクセス可能となる。
      flash[:success] = "Welcome to the Sample App!"

      # 以下は、redirect_to("/users/#{@user.id}")と同じ意味
      # @userに飛ばしたいって？んじゃぁ、users_urlに、@user.idを渡すってことだね？OK　ってな感じ
      # ちなみに、users_urlときたら、"/users"と解釈してくれる。
      redirect_to @user
    else
      render 'new'
    end
  end

  private
    # ユーザーオブジェクトのうち、更新可能なパラメータを制限
    # 他のパラメータ（キー）は無視される(セキュリティ担保)
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(user)
    # session(Railsで事前定義済み)メソッドは、ハッシュライクに扱える
    # 以下を実行することで、ユーザーのブラウザ内の一時cookiesに
    # 暗号化済みのユーザーIDが自動で作成される
    session[:user_id] = user.id
  end

  # ユーザーのセッションを永続的にする
  def remember(user)
    # userインスタンスのrememberメソッドを呼ぶ
    user.remember
    # 永続的クッキーに署名付きで（暗号化された）user_id格納
    cookies.permanent.signed[:user_id] = user.id
    # さらに、トークンを格納する。
    cookies.permanent[:remember_token] = user.remember_token
  end

  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    # セッションが有効ならセッションからカレンとユーザーを確定
    # ちなみに、@変数はインスタンス変数（その場で定義して、以降使える）
    # さらに、self.変数もインスタンス変数だが、アクセサ定義されたもの
    # class Foo
    #   attr_reader :hoge
    # ときたら、self.hogeでアクセスできる。また、@hogeでもアクセス可。
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    # セッションが無い場合かつクッキーが存在すれば、クッキーからユーザーを確定
    elsif (user_id = cookies.signed[:user_id])
      #raise       # テストがパスすれば、この部分がテストされていないことがわかる
      user = User.find_by(id: user_id)
      # userが存在し、認証できたら、ヘルパーのlog_inメソッドを呼び、
      # current_userにuserを格納する
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # 永続的セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, size: 80)

    # メールからハッシュの値を求め、gravatarのidとする
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)

    # urlを作成(ex. "https://secure.gravatar.com/avatar/23jkosoohogehoge?s=80"
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"

    # イメージタグを作成する
    # image_tagは、ActionView::Helpers::AssetTagHelperクラスのメソッド
    image_tag(gravatar_url, alt: user.name, class: "gravatar")

  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", '/login' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all',
                        'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application',
                        'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%# 中身がmessage文字列で、alert alert-?クラスのdivタグを生成  %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      
      <%# 開発モードならパラメータをダンプする %>
      <%= debug(params) if Rails.env.development? %>

    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>StaticPages#about</h1>
<p>
  <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  is a <a href="https://railstutorial.jp/#ebook">book</a> and
  <a href="https://railstutorial.jp/#screencast">screencast</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>StaticPages#contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>StaticPages#help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="https://railstutorial.jp/help">
    Rails Tutorial help page
  </a>.
  To get help on this sample app, see the
  <a href="https://railstutorial.jp/#ebook">
    <em>Ruby on Rails Tutorial</em> book
  </a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
<h1>Welcome to the Sample App</h1>
<h2>
  This is the home page for the
  <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  sample application.
</h2>
<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

<%#= image_tag("kitten.jpg", alt: "猫") %>
<%# railsでは、コメントはこのように書けばよいのかぁ。。 %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>